OHDSI/Achilles

inst/sql/sql_server/Achilles_v4.sql
Closes #23
It's not the best phrasing, but it was the most concise change.  I had considered changing the message to: "Distribution of age in condition occurrence by condition_concept_id" but that didn't read much better.
=> Distinguish queries 406/1006, 706/906

Dockerfile, README.md, docker-compose.yml.sample, docker-run, env_vars.sample
A Dockerfile is added that starts from a standard R image,
installs all Achilles requirements, installs Achilles from source,
and defines the (new) docker-run script as the default command.
Sample docker-compose and env_var files are added and instructions for
the entire setup and run process, including creating live versions of
those files, are added to the README.
Signed-off-by: Aaron Browne <aaron0browne@gmail.com>
=> Add docker usage alternative

README.md
Reordered install_github commands (SQLRender must come before DatabaseConnector)
=> Reordered install_github commands

Dockerfile, docker-run
Remove specification of openjdk version because old versions are
apparently not available on the debian repos and version scoping doesn't
seem possible given the version string format.
Add installation of libssl-dev and libxml2-dev to the OS and rjson to R.
These must be new dependencies, because the installation was working
previously.
Fix Achilles installation typo (`R COMMAND INSTALL` to `R CMD INSTALL`).
Fix permissions of created output dir to match Achilles-created dir
permissions ("0755").
Update `achilles` and `exportToJson` function call signatures to use
`cdmDatabaseSchema` instead of outdated `cdmSchema` (and corresponding
`results...`) arguments.
Signed-off-by: Aaron Browne <aaron0browne@gmail.com>
=> Squash bugs in Docker deployment

inst/sql/sql_server/AchillesHeel_v4.sql
If a given analysis ID (e.g., 3) is checked for multiple errors, we need to add a sub-id to the Heel rule
like here
--ERROR:  year of birth in the future
INSERT INTO @results_database_schema.ACHILLES_HEEL_results (
analysis_id,
ACHILLES_HEEL_warning
)
SELECT DISTINCT or1.analysis_id,
'ERROR: ' + cast(or1.analysis_id as VARCHAR) + '-' + oa1.analysis_name + '; should not have year of birth in the future, (n=' + cast(sum(or1.count_value) as VARCHAR) + ')' AS ACHILLES_HEEL_warning
FROM @results_database_schema.ACHILLES_results or1
INNER JOIN @results_database_schema.ACHILLES_analysis oa1
ON or1.analysis_id = oa1.analysis_id
WHERE or1.analysis_id IN (3)
AND CAST(or1.stratum_1 AS INT) > year(getdate())
AND or1.count_value > 0
GROUP BY or1.analysis_id,
oa1.analysis_name;
--WARNING:  year of …
=> subID for heel checks on achilles IDs

README.md
Hi,
I just updated the README to include the cdmVersion parameter while running Achilles. For cdm v5, the user needs to specify this parameter or Achilles doesn't run successfully.
Best,
Aarti
=> Changed the README to include cdmVersion parameter

inst/sql/sql_server/export_v5/condition/sqlConditionTreemap.sql, inst/sql/sql_server/export_v5/conditionera/sqlConditionEraTreemap.sql, inst/sql/sql_server/export_v5/drug/sqlDrugTreemap.sql, inst/sql/sql_server/export_v5/drugera/sqlDrugEraTreemap.sql, inst/sql/sql_server/export_v5/observation/sqlObservationTreemap.sql, inst/sql/sql_server/export_v5/procedure/sqlProcedureTreemap.sql
Resolves Issue #81. Please note that vocabulary_id is still referenced in these scripts in order to build out hierarchies to ATC and MedDRA.
=> V5 Treemap - use domain_id

Dockerfile, README.md
Also install as many packages from Rutter's PPAs as possible.
Not basing on the r-base image has the disadvantage that it's not possible to pin a specific R version, but that was a bad idea anyway, since quite a few packages were installed from source and CRAN packages tend to drop support for old R versions relatively quickly.
Another big problem with the previous setup was the unholy mix of packages from debian unstable. In fact, the image didn't even build without extra parameters given to apt.
Finally, also leave only output and docker-run under /opt/app after installation.
=> docker: Use ubuntu:14.04 and Rutter's PPAs

inst/csv/achilles_rule.csv, inst/sql/sql_server/AchillesHeel_v5.sql, inst/sql/sql_server/Achilles_v5.sql
-new iris measure (patients with no visits) + new related rule 32 for that #100
-new derived analyses/measures #106
-calculations for rules are stored in derived measures and the resulting rule is simple #116
-new rule 31 (patient/provider ratio) (too few providers and too many patients)
-new rule for unmapped data (and derived measures)
=> 2 new rules 31 and 32  and new derived analyses

inst/sql/sql_server/Achilles_v4.sql
4 queries (116,604,704,1503) are missing schema aliases.
=> Fix bugs in Achilles_v4.sql

README-impala.md, inst/sql/sql_server/Achilles_v5.sql
This PR includes the changes I needed to run all the Achilles v5 queries on Impala. Impala is strict about types, so mostly it is adding CASTs in the right places.
Note that it relies on the Impala changes in DatabaseConnector and SqlRender, but since these have been committed they are picked up automatically.
=> Run on Impala

README-impala.md, inst/sql/sql_server/Achilles_v5.sql
This reverts the change to quote the 'location' table, and handles it in the Impala dialect of SqlRender, see https://github.com/OHDSI/SqlRender/compare/master...tomwhite:impala-location-reserved-word.
I have successfully tested this change on all the Achilles tables.
=> Remove back-quoted 'location' field and handle in SqlRender

.travis.yml, tests/testthat.R
This is to remove the filter from the test_check to only look at mssql tests.  This will verify if the TravisCI will execute without timeout across all dbms.
=> Remove mssql filter from testthat.

R/exportToJson.R, inst/sql/sql_server/export_v5/domainmeta/sqlDomainMeta.sql
Uses DatabaseConnector's getTableNames function to grab available tables to check if CDM_DOMAIN_META is present. Earlier logic was misusing R's try function.
=> Fixes logic for handling if CDM_DOMAIN_META table is not present.

inst/sql/sql_server/Achilles_v5.sql
This is a small bug fix as order by statements within an insert are not supported by some sql languages.
=> Removed 'order by' statement in the insert for analysis_id 1900

inst/sql/sql_server/AchillesHeel_v5.sql
The string "births" was misspelled "birhts" as per https://github.com/OHDSI/Achilles/issues/222
=> Fixes "birhts" typo (#222)

R/Achilles.R, inst/sql/sql_server/Achilles_indices_v5.sql
Conditionally adding a clustered columnstore index to ACHILLES_results when the DBMS is Microsoft APS (aka PDW). Without this index, we were finding that queries that attempted to CAST(stratum_1, int) would fail which was causing problems upstream with WebAPI.
If approved, it would be great if this could be a v1.5.1 release of Achilles to include this fix. Thanks!
=> Conditionally applying a clustered columnstore index for pdw

R/Achilles.R
Fixes https://github.com/OHDSI/Achilles/issues/225
RStudio complained about 'java.sql.SQLDataException: ORA-01861:
literal does not match format string' and could only get 44%
through the initial Achilles run.
The underlying problem was tied to the use of CAST on an Oracle
datefield in the SQL command shown in the errorReport.txt file.
CASE is good because it is ANSI standard sql but it presupposes
the date format is 'YYYYMMDD'.
=> forcibly change NLS_DATE_FORMAT to 'YYYYMMDD' for oracle flavors

inst/sql/sql_server/AchillesHeel_v5.sql
A fix for cross joins was put in this commit: https://github.com/alistairewj/Achilles/commit/55a470ad2fdf1d372cf471197843f6a9518c132e
There were an additional 3-4 statements that needed the fix which I've added here, see #266 for detail on the error.
=> additional cross join fixes for #260, #266

R/Achilles.R, R/exportToJson.R
Achilles.R was displaying all run durations as seconds, regardless of if the value represented minutes (or otherwise). Modified it to show the correct units in a similar fashion to R/exportToJson.R
=> Swapped static "secs" for time units calculation

DESCRIPTION, R/Achilles.R, R/AchillesHeel.R, R/AchillesViewResults.R
Fixes #365 , the SqlRender in DEPENDS section as @schuemie raised in #133 
(renderSql becomes render, translateSql becomes translate). Moved SqlRender to IMPORTS section of Description file, and added requirement for the minimum version of 1.6.0
=> Updated usage of SqlRender functions 

R/Achilles.R
without fix, code throws error "object 'sqlFilename' not found" because the object is actually named 'sqlFileName' with a capital N
=> bug fix - capitalization typo 'sqlFileName'

docker-run
docker-run script still supply cdmVersion parameter to exportToJson whereas
R/exportToJson no longer expect it which cause docker mode execution failure
=> issue-402-fix-docker-run-exportToJson-call

R/Achilles.R
Exclude impala from supported temp tables DBs.
Closes #413
=> Exclude impala from supported temp tables DBs

inst/sql/sql_server/analyses/1003.sql, inst/sql/sql_server/analyses/1020.sql, inst/sql/sql_server/analyses/200.sql, inst/sql/sql_server/analyses/201.sql, inst/sql/sql_server/analyses/202.sql, inst/sql/sql_server/analyses/204.sql, inst/sql/sql_server/analyses/206.sql, inst/sql/sql_server/analyses/211.sql, inst/sql/sql_server/analyses/220.sql, inst/sql/sql_server/analyses/403.sql, inst/sql/sql_server/analyses/420.sql, inst/sql/sql_server/analyses/502.sql, inst/sql/sql_server/analyses/603.sql, inst/sql/sql_server/analyses/620.sql, inst/sql/sql_server/analyses/703.sql, inst/sql/sql_server/analyses/720.sql, inst/sql/sql_server/analyses/803.sql, inst/sql/sql_server/analyses/820.sql, inst/sql/sql_server/analyses/903.sql, inst/sql/sql_server/analyses/920.sql
As the CDM now allows records outside the observation period - this messes up some of the achilles plots.
I edited the data dashboard and visit analyses to restrict to things that overlap with an observation period.
for analysis 211 - I restricted to visits contained within an observation period rather than overlapping
=> Restricting to observation period

README.md
cdmVersion is not an argument to the exportToJson function.
=> Fix exportToJson() example in README.md

Dockerfile
This updates the base image to Ubuntu 20.4, OpenJDK to 11 (using JRE instead of JDK) and runs the resulting container as a non-root user "achilles" by default.
Note that I also had to apply https://github.com/OHDSI/Achilles/pull/503 for the build to work properly, although a added it to a different install section.
=> Update container base and run as non-root by default

R/Achilles.R, inst/csv/achilles/achilles_analysis_details.csv, inst/sql/sql_server/analyses/1824.sql, inst/sql/sql_server/analyses/424.sql, inst/sql/sql_server/analyses/624.sql, inst/sql/sql_server/analyses/724.sql, inst/sql/sql_server/analyses/824.sql, man/achilles.Rd
The co-occurrence queries have been optimized to address issue #425 
The before and after is below (against a MDCD db):
Original:
```
Analysis     Time
---------    -----
424          (1.1 hours)
624          (41 mins)
724          (18 mins)
824          (4 mins)
1824         (9 mins)
TOTAL: ~2hr 20 min
```
```
Analysis     Time
---------    -----
424          (40 mins)
624          (10 mins)
724          (6 mins)
824          (20 mins)
1824         (2 mins)
TOTAL: ~1hr 18 minutes
```
Even with the optimizations, these analyses will run more slowly on dbs larger than MDCD, therefore, the main Achilles function was modified to accept a defaultAnalysesOnly parameter to indicate whether or not you want to run the co-occurrence queries. By default, they will not be run.  This was achieved by …
=> Fixes Issue 425

inst/sql/sql_server/analyses/109.sql
By treating a date string, "YYYYMMDD", as an 8 digit integer, we can perform this analysis without worrying about functions.
Tested successfully on both Oracle and Redshift databases.
=> Fixes #473 by converting dates to 8 digit integers

inst/sql/sql_server/export/observationperiod/cumulativeduration.sql
Multiplication in "group by" was removed
fixes https://github.com/OHDSI/Achilles/issues/527
=> Big query can not recognize that column is used in group by clause when multiplication is used

R/exportToJson.R
Supports #529.
Since HEEL analyses are disabled by default, heel report generation will also be disabled by default in the export.
=> Removing default HEEL report generation in exportToJson

inst/sql/sql_server/analyses/117.sql
fixes https://github.com/OHDSI/Achilles/issues/532
I've tried several different changes of sql code and this modification has better or similar execution plan and better execution time (tested on postgres, ms sql, netezza and hive)
=> Big query does not allow to use join without a condition that is an equality of fields from both sides of the join

DESCRIPTION, inst/sql/sql_server/analyses/11.sql
Changed 'not in' logic in analysis 11 to use not exists, which is better for Spark performance. Also updated my email address.
=> Changed 'not in' logic in analysis 11

inst/sql/sql_server/analyses/109.sql
@fdefalco 
This query is slightly different than 117 in that we just need the first and last day of each year.   I used your method from 117 to generate the dates, then just kept the ones needed for later in the query. 
Tested successfully and compared against previous results from 109, against flatiron and mdcr.
=> Fixes #573

inst/csv/achilles/achilles_analysis_details.csv, inst/sql/sql_server/analyses/414.sql, inst/sql/sql_server/analyses/415.sql, inst/sql/sql_server/analyses/416.sql
Added new analyses 414, 415, and 416.  These reports count records (within a valid OP) in CONDITION_OCCURRENCE stratifying by:
414: condition_status_concept_id
415: condition_type_concept_id
416: condition_status_concept_id, condition_type_concept_id
To test:
```r
Achilles::achilles(
connectionDetails = connectionDetails,
outputFolder = "/TMP",
analysisIds = c(414,415,416),
updateGivenAnalysesOnly = T,
createTable = F
)
```
This was successfully tested against two databases in the ops environment.
=> added reports for new condition_occurrence fields

inst/sql/sql_server/analyses/1203.sql, inst/sql/sql_server/analyses/1900.sql
Here are the updates to Achilles to support cdm v5.4.  After discussing with @clairblacketer , we decided to leave cdmVersion as is for now.  I will create a forum post explaining upcoming future changes to cdmVersion and why cdm_source is important.
This was successfully tested multiple ways against three databases.  This was tested by running Achilles against databases with both v5.3.1 and v5.4 CDMs.  The cdm version, if not given, is determined by CDM_SOURCE and need not be supplied.  To test, you can run something similar to the following:
```r
connectionDetails <- DatabaseConnector::createConnectionDetails( rdbms, server, etc... )
cdmDatabaseSchema     <- "cdm_v540"
resultsDatabaseSchema <- "results_v540"
Achilles::achilles(
connectionDetails = connectionDetails,
cdmDatabaseSchema = …
```
=> V5.4 support

inst/sql/sql_server/analyses/109.sql
Tested successfully on redshift.  To test:
```
create table ar_109 as 
select * from achilles_results where analysis_id = 109
Achilles::achilles(
connectionDetails = connectionDetails,
outputFolder = "output_folder",
analysisIds = c(109),
updateGivenAnalysesOnly = T,
createTable = F
)
-- NON-ZERO IMPLIES ERROR!
select count(*) from (
select * from achilles_results where analysis_id = 109
except
select * from ar_109
) tmp
```
=> Fixes issue #600

R/performTemporalCharacterization.r, man/performTemporalCharacterization.Rd
Successfully tested on redshift.  The parameter, outputFile, now defaults to "temporal-characterization.csv" and is created in pwd if not otherwise specified.  To test:
```
Achilles::performTemporalCharacterization(
connectionDetails     = connectionDetails,
cdmDatabaseSchema     = cdmDatabaseSchema,
resultsDatabaseSchema = resultsDatabaseSchema)
```
=> Fixes issue #622

inst/sql/sql_server/summary/dbSourceVocabs.sql, inst/sql/sql_server/summary/dbVisitDist.sql
This commit adds a count to the source vocab query and then rolls up the visit query to their terminal ancestor.
=> Adds count to dbSummary queries

R/Achilles.R
Successfully tested on redshift against cdm v5.3, using the following two test cases:
```r
Achilles::achilles(connectionDetails = connectionDetails,
cdmVersion = "5.3",
outputFolder = "D:/sandbox/Achilles")
analysisDetails <- Achilles::getAnalysisDetails()
excludeAnalysisIds <- analysisDetails[analysisDetails$IS_DEFAULT==0,]$ANALYSIS_ID
Achilles::achilles(connectionDetails = connectionDetails,
cdmVersion = "5.3",
excludeAnalysisIds = excludeAnalysisIds,
outputFolder = "D:/sandbox/Achilles")
```
=> Fixes #651

inst/sql/sql_server/analyses/1814.sql
Tested successfully against CDM v5.3 and v5.4 on redshift.
To test on v5.3
```r
Achilles::achilles(connectionDetails = connectionDetails,
cdmVersion = "5.3",
createIndices = FALSE,
analysisIds = c(1814),
updateGivenAnalysesOnly = T,
createTable = F,
outputFolder = your_output_folder)
```
=> Fixes #655

R/Achilles.R, inst/sql/sql_server/analyses/achilles_analysis_ddl.sql
To address this issue, the fix creates the achilles_analysis table from a pre-existing sql script, rather than generate it dynamically using CTAS and union-all.  The table is populated using the data from the achilles_analysis_details.csv.  This was successfully tested against cdm v5.3 on redshift.  To test:
```r
Achilles::achilles(connectionDetails = connectionDetails,
cdmVersion = "5.3")
Achilles::runMissingAnalyses(connectionDetails = connectionDetails,
resultsDatabaseSchema = resultsDatabaseSchema)
Achilles::achilles(connectionDetails = connectionDetails,
cdmVersion = "5.3", …
```
=> Fixes #657

inst/sql/sql_server/analyses/532.sql
Fixes #691 
I had recently removed this from other analyses (casting to FLOAT instead), but must have missed 532.
=> Removed NUMERIC(7,6) from analysis 532

.Rbuildignore, .lintr, DESCRIPTION, R/exportToAres.R, man/exportToAres.Rd
The idea of the change is to save all concept data in one go when we write to DuckDB instead of iterating through concept_ids as we have to do when saving JSONs.
=> Duckdb export performance

R/getTemporalData.r
When connection details is set up using Connection String, server value is NULL. It caused failure on attempt to extract dbName from server.
Now, dbName is set to NA if server is not provided (new behavior) as well as when it doesn't contain slash character ("/") (existent behavior)
=> Fix failure on missing server value in getTemporalData

inst/sql/sql_server/analyses/117.sql
Since HAVING clause removes records which don't match obs_month, we can use INNER JOIN here.
This is to address problem in Databricks where small table in LEFT JOIN is not broadcasted when it's on left side.
Related issue #690
=> Improve performance of analysis 117
