- Dockerfile
Fixes #66
Signed-off-by: Aaron Browne <aaron0browne@gmail.com>
> Update openjdk req in dockerfile

- inst/sql/sql_server/AchillesHeel_v4.sql
- inst/sql/sql_server/AchillesHeel_v5.sql
this updated file has v4 rules on top and after those a copy of applicable rules from the v5 file
> rule ID changes for the v4 heel file

- inst/sql/sql_server/AchillesHeel_v4.sql
- inst/sql/sql_server/AchillesHeel_v5.sql
ACHILLES_HEEL_results.record_count type change to BIGINT
> ACHILLES_HEEL_results.record_count type change to BIGINT

- inst/sql/sql_server/AchillesHeel_v4.sql
v4 only has vocabulary_id checks.
fixes #85.
> Revert changes made to look for domain_id.  

- inst/sql/sql_server/export_v4/achillesheel/sqlAchillesHeel.sql
I removed the qualifier in lines 1 & 3.  Testing completed.
> Fix for qualifier in the sqlAchillesHeel.sql for V4

- inst/sql/sql_server/Achilles_v5.sql
Very similar to issue #108. Sorry, I only later discovered it.
> Fully qualify `LOCATION` in Achilles_v5.sql (fixes #111)

- inst/sql/sql_server/AchillesHeel_v5.sql
(all changes are in the Heel SQL file only)
-new rule 31 about provider/patient ratio
-new comments added to Heel SQL file 
-extending achilles derived table with measure_id and new derived analyses (rules on them are pending development)
(PR purpose is to get back in sync with master branch (new release)
changes are related to #116 and #106
> new rule 31 and other changes

- DESCRIPTION
- inst/sql/sql_server/AchillesHeel_v5.sql
- inst/sql/sql_server/Achilles_v5.sql
new rules 32,33 and 34 and few new analyses
- Concept_0 report incorporated into main Achilles SQL file (#72)
- one new analysis (#125)
- new derived analyses (#106)
- new rule 33 (first example of general population rule only) 
- update of R package version
(tested on MS SQL and Redshift and it works fine)
> new rules 32,33 and 34 and updates and one new analysis

- inst/sql/sql_server/AchillesHeel_v5.sql
- inst/sql/sql_server/Achilles_v5.sql
only SQL changes, tested on postgres and mysql (and now on Travis)
#106 new analyses 
- New measure 212 added for visit type
- new derived measure for death data
- new derived measure for Data Quality study (size of Achilles metadata; informative non sensitive dataset info)
> New measures for data characterization and Heel 

- README-impala.md
- inst/sql/sql_server/Achilles_v5.sql
* Change 'stats' to 'statsView' as STATS is a reserved word in Impala
* Cast avg and stdev to float.
* Quote 'location' since it is a reserved word in Impala
* Cast as FLOAT
* Add README for Impala
* Concat
* Cast as VARCHAR(255)
> Run on Impala (#178)

- inst/sql/sql_server/Achilles_v4.sql
> Added missing table qualifier for drug_cost in rule 1502 (v4)

- README-impala.md
... and use TIMESTAMP type for dates. See http://forums.ohdsi.org/t/date-support-in-impala/2599.
> Update Impala notes to use Parquet-based CDM schema

- inst/sql/sql_server/export_v5/measurement/sqlMeasurementsByType.sql
- inst/sql/sql_server/export_v5/measurement/sqlRecordsByUnit.sql
- inst/sql/sql_server/export_v5/measurement/sqlValuesRelativeToNorm.sql
Update export scripts to refer to correct results table.
> Fixes #200.

- DESCRIPTION
- R/Achilles.R
- R/AchillesViewResults.R
- R/exportToJson.R
There is a new version of DatabaseConnector coming that drops the dependency on RJDBC. Achilles was using the dbDisconnect and dbGetQuery functions which belonged to that package.
> Updating to new DatabaseConnector interface

- DESCRIPTION
- inst/csv/achilles_rule.csv
updating version in two places
> v1.5 tiny edits

- inst/sql/sql_server/Achilles_v5.sql
> Fixes for queries 691, 791, 891, 1891 for Impala.

- R/Achilles.R
Reverting OHDSI/Achilles#229 as this issue may be adrssed by https://github.com/OHDSI/Achilles/pull/233
> Revert "forcibly change NLS_DATE_FORMAT to 'YYYYMMDD' for oracle flavors"

- inst/sql/sql_server/AchillesHeel_v5.sql
- inst/sql/sql_server/Achilles_v4.sql
Fixes #239 
This change depends on a new release of SqlRender.  So please hold off on merging until the Oracle rules are updated.  see OHDSI/SqlRender#98
Tagging @schuemie for awareness.
> Fix VARCHAR on Oracle

- docker-run
- inst/sql/sql_server/AchillesHeel_v5.sql
- inst/sql/sql_server/Achilles_v5.sql
- inst/sql/sql_server/ConceptHierarchy_v5.sql
Reverts OHDSI/Achilles#245
due to group by error on one of the query and incorrect merging done by me.
> Revert "Add CAST to provide Achilles run over Impala CDM"

- Dockerfile
* Indices creation skip if netezza
* fix
* fix dependencies in Dockerfile
> Docker image build fails (#273)

- docker-run
* Indices creation skip if netezza
> Added indices creation skip if netezza (#238)

- inst/sql/sql_server/export/procedure/sqlProcedureTreemap.sql
- inst/sql/sql_server/heels/parallel/heel_results/rule_18.sql
- inst/sql/sql_server/heels/parallel/heel_results/rule_24.sql
- inst/sql/sql_server/heels/parallel/heel_results/rule_25.sql
- inst/sql/sql_server/heels/parallel/heel_results/rule_26.sql
- inst/sql/sql_server/heels/parallel/heel_results/rule_3.sql
- inst/sql/sql_server/heels/parallel/results_derived/13.sql
- inst/sql/sql_server/heels/parallel/results_derived/26.sql
- inst/sql/sql_server/heels/serial/rule_28.sql
- inst/sql/sql_server/post_processing/concept_hierarchies/procedure.sql
* Indices creation skip if netezza
* fix
* Fixes Achilles run on Impala database
> Impala fixes (#336)

- Dockerfile
- docker-run
Fixes https://github.com/OHDSI/Achilles/issues/350
> Fixed Docker & added multi-threading  param to it

- R/Achilles.R
Fixes https://github.com/OHDSI/Achilles/issues/353
> Fixed finally clauses in tryCatch to avoid growing number of DB connections

- R/Achilles.R
> Run Achilles with analysisId = 1425 only CDM with version >= 5.3 

- R/Achilles.R
- inst/sql/sql_server/analyses_v6/500.sql
- inst/sql/sql_server/analyses_v6/501.sql
- inst/sql/sql_server/analyses_v6/504.sql
- inst/sql/sql_server/analyses_v6/505.sql
- inst/sql/sql_server/analyses_v6/506.sql
I am attempting to run the cdm_v6 branch on my OMOP cdm, and running into many bugs. Here are some fixes I've made so far.
I would not yet accept commit 4318a84, as I am running into issues around those lines of code. I will update this pull request if I find the solution - in the meantime please lmk if you know the fix. The error is detailed in issue #396 
Additionally - is cdm_v6 expected to work in its current state? is it actively being developed? 
Thanks!
> bug fixes in cdm_v6 branch

- Dockerfile
> Dockerfile - fix broken cran mirror link

- Dockerfile
Upgrade image from Ubuntu:Trusty --> Ubuntu:Xenial, Java 7 --> Java 8.
> Fixes #479. 

- inst/csv/achilles/achilles_analysis_details.csv
- inst/sql/sql_server/analyses/1203.sql
This new analysis addresses WebAPI issue [#735](https://github.com/OHDSI/WebAPI/issues/735#issuecomment-700685676)
> added analysis 1203 to address issue #735

- inst/sql/sql_server/export/datadensity/conceptsperperson.sql
- inst/sql/sql_server/export/datadensity/recordsperperson.sql
- inst/sql/sql_server/export/datadensity/totalrecords.sql
> Add Measurement data over time in the Data Density Plot

- Dockerfile
> add missing readr dependency in Docker build

- R/Achilles.R
I implemented it simply.
If you let me know what to modify, I will apply it.
> Add Total Runtime to Output #459

- inst/sql/sql_server/analyses/117.sql
Resolves https://github.com/OHDSI/Achilles/issues/516
> fix for possible missing date keys

- R/exportToJson.R
- inst/sql/sql_server/export/domainmeta/sqlDomainMeta.sql
- inst/sql/sql_server/export/metadata/sqlCdmSource.sql
- inst/sql/sql_server/export/metadata/sqlMetadata.sql
> update to current metadata standard

- inst/csv/achilles/achilles_analysis_details.csv
- inst/sql/sql_server/analyses/226.sql
- inst/sql/sql_server/export/visit/sqlDomainVisitStratification.sql
> adding domain record stratification by visit

- inst/sql/sql_server/heels/parallel/results_derived/24.sql
> fix logical bug of 'Death:BornDeceasedRatio'

- inst/sql/sql_server/export/condition/sqlConditionTreemap.sql
- inst/sql/sql_server/export/condition/sqlConditionsByType.sql
- inst/sql/sql_server/export/condition/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/conditionera/sqlConditionEraTreemap.sql
- inst/sql/sql_server/export/conditionera/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/death/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/drug/sqlDrugTreemap.sql
- inst/sql/sql_server/export/drug/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/drugera/sqlDrugEraTreemap.sql
- inst/sql/sql_server/export/drugera/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/measurement/sqlMeasurementTreemap.sql
- inst/sql/sql_server/export/measurement/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/measurement/sqlValuesRelativeToNorm.sql
- inst/sql/sql_server/export/observation/sqlObservationTreemap.sql
- inst/sql/sql_server/export/observation/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/observationperiod/observationlengthbyage.sql
- inst/sql/sql_server/export/procedure/sqlPrevalenceByGenderAgeYear.sql
- inst/sql/sql_server/export/procedure/sqlProcedureTreemap.sql
- inst/sql/sql_server/export/visit/sqlPrevalenceByGenderAgeYear.sql
> Changed use of + for string concat to concat() function in export SQLs

- inst/sql/sql_server/export/observationperiod/cumulativeduration.sql
fixes https://github.com/OHDSI/Achilles/issues/527
> SqlRender cannot correctly translate multiplication in group by clause when column name is not last

- R/Achilles.R
This has been tested successfully against an Oracle database.
Since oracle temp tables are not created as true temp tables (that would merely vanish up session disconnect), they need to be explicitly removed.
> Fixes #466

- R/exportToJson.R
- inst/sql/sql_server/export/condition/sqlConditionsByType.sql
- inst/sql/sql_server/export/observationperiod/cumulativeduration.sql
- man/dropAllScratchTables.Rd
> update for condition type

- R/Achilles.R
- inst/csv/achilles/achilles_analysis_details.csv
- inst/sql/sql_server/analyses/create_analysis_table.sql
this pr introduces the concept of analysis categories that can be used to improve performance characterization in down stream systems.
changed default to is_default to avoid database reserved word collisions with default.
Also closes #386.
> analysis definition additions

- inst/sql/sql_server/export/condition/sqlConditionsByType.sql
fixes https://github.com/OHDSI/Achilles/issues/527
> Big query does not allow to use columns with aggregation functions in "GROUP BY" clause

- inst/sql/sql_server/export/drug/sqlDrugTreemap.sql
- inst/sql/sql_server/export/drugera/sqlDrugEraTreemap.sql
> include CVX in analysis exports

- DESCRIPTION
- README.md
To test:
remove.packages("Achilles")
remove.packages("Castor")
devtools::install_github("OHDSI/Achilles", ref = "issue-568")
If the changes to the DESCRIPTION file are correct, the above commands should ask you to install Castor as part of the Achilles install (for testing purposes, you can ignore package update that Castor requires).
> Issue 568 - Fixes Castor package dependency error

- R/createTimeSeries.r
- R/getTemporalData.r
- inst/sql/sql_server/temporal/achilles_temporal_data.sql
Removed ORDER BY and cross join to CDM_SOURCE to improve performance, and made corresponding changes to the creation of time series.  Successfully tested against optum ehr.
> Temporal characterization performance optimizations

- inst/csv/achilles/achilles_analysis_details.csv
- inst/sql/sql_server/analyses/2004.sql
Creating pull request for domain overlap work.
> Adding analysis 2004 - Domain overlap

- R/generateDomainOverlapSql.R
This script will be useful should users want to add / remove a domain to / from the overlap analysis.
> Script to generate SQL for domain overlap (2004).

- R/Achilles.R
- man/achilles.Rd
Added optional parameter, excludeAnalysisIds, to enable a user to specify which analyses NOT to run.
> issue #613

- R/exportAO.R
- inst/sql/sql_server/export/datadensity/totalrecords.sql
update to which analysis retrieves total people
addition of condition era to ao export
> fixes to include condition era reports and correct people count

- R/Achilles.R
> Snowflake dialect support

- inst/csv/achilles/achilles_analysis_details.csv
This should move all data quality related checks out of the default analyses.
> Remove dq checks from default

- R/Achilles.R
Fixes #701 and some refactoring. 
See in-line comments explaining the main changes.
> Reintroduce time unit for performance benchmarking

- inst/csv/achilles/achilles_analysis_details.csv
Added 2120 to achilles_analysis_details.csv:
```r
x <- Achilles::getAnalysisDetails()
x[x$ANALYSIS_ID == 2120,c(1,2,4,5,10)]
ANALYSIS_ID   DISTRIBUTION                                                     ANALYSIS_NAME STRATUM_1_NAME IS_DEFAULT
2120              0 Number of device_exposure records by device_exposure start month calendar month          1
```
> Fix for Issue 712

- .github/workflows/R_CMD_check_main_weekly.yaml
- R/exportToJson.R
This is a possible fix for #726
> Fix fromJSON correct method usage

- R/exportToAres.R
- inst/sql/sql_server/analyses/1100.sql
- inst/sql/sql_server/analyses/1101.sql
- inst/sql/sql_server/analyses/1102.sql
- inst/sql/sql_server/analyses/1103.sql
- inst/sql/sql_server/export/location/sqlLocationTable.sql
Added export of location data (analyses 1100 - 1103) to location.csv to exportToAres
> Location table export to ares
